### ISSUE TITLE
Failed to find checkpoint

### ISSUE THREAD

**Issue by joy-yjl** [kskin/WaterGAN#1]
When I do as readme to train the model. There always been "Failed to find check point". I found the checkpoint is empty. So I can load nothing.  By the way, I found the dataset don't have depth information.

**Comment by zhengziqiang** [comment]
I met the same error.

**Comment by kskin** [comment]
Please make sure your directory is set up as follows:

WaterGAN/
    data/
        air_images/
           *.png
        air_depth/
            *.mat
        water_images/
            *.png

The in air depth and images should be 480 (height) × 640 (width). It should fail to find a checkpoint for your first time training. There is no depth required for the real underwater data.

**Comment by LongChenCV** [comment]
Thanks for sharing this code.  Could you share the checkpoint file?
When running the source code, following problem arises:
[*] Failed to find a checkpoint
 [!] Load failed...
