### ISSUE TITLE
Datasets unavailable

### ISSUE THREAD

**Issue by cheffe112** [kskin/WaterGAN#2]
Hello, I've tried to download the datasets from https://www.umich.edu/~dropda/Jamaica.tar.gz and https://www.umich.edu/~dropopen/MHL.tar.gz, respectively.
Both links only threw a "University of Michigan Weblogin" form on me. Could you have a look and maybe upload the datasets elsewhere if necessary?
Thanks!

**Comment by cheffe112** [comment]
Okay, so now I've created such a "U-M friend account" and logged in, only to get a "404 - page not found" error. :-(

**Comment by cheffe112** [comment]
Hello, @kskin, any input on this?

**Comment by kskin** [comment]
Please use the links http://www.umich.edu/~dropda/Jamaica.tar.gz and
http://www.umich.edu/~dropopen/MHL.tar.gz
