### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by IPNUISTlegal** [kskin/WaterGAN#3]
I strictly follow your requirements to establish directory structure.  Air_depth (*.mat) seems that there is no download link or data.Watergan can generate synthetic underwater image without air_depth?
![image](https://user-images.githubusercontent.com/35527568/45581524-38c6dd80-b8d2-11e8-90fc-add1df3e92b2.png)
IndexError: list index out of range.  I think that depth_batch_files is empty，which means we have no depth data. So, Watergan maybe needs  air_depth.
![image](https://user-images.githubusercontent.com/35527568/45581650-c5729b00-b8d4-11e8-8fa2-a39cb2b5fbd1.png)
I can't find image restoration network in your code.It is convenient for your to share these codes?
sorry to ask you so many questions, thanks  a lot !

**Comment by djjandXMU** [comment]
You should download NYU dataset.Then you can load the nyu_depth_data_labeled by MATLAB.After that,you can check out the variables about the .mat, you will find 2200+images. Next, you could read this images and depth.mat and save it by yourself. I have trained the model sucessfully. But as for the correction model, I have no idea.

**Comment by IPNUISTlegal** [comment]
@djjandXMU  同学你好，为了方便，我打中文了。我已经下载了NYU RGB-D dataset， 空气中的图像已经放到air_images，深度信息（mat文件）已经放到air_depth当中。   一运行mainjamaica.py，https://github.com/kskin/WaterGAN/blob/3ad47608d20a9651fdf36ecb38b236e0942fae7b/modeljamaica.py#L743 就会报错ValueError: 'arr' does not have a suitable array shape for any mode. 请问你方便分享代码吗

**Comment by djjandXMU** [comment]
同学你好，我最近正在复现它的后半部分代码，我将会一并公布，请耐心等待一下------------------ 原始邮件 ------------------
发件人: "lihanyu1204"<notifications@github.com>
发送时间: 2019年6月11日(星期二) 晚上7:26
收件人: "kskin/WaterGAN"<WaterGAN@noreply.github.com>;
抄送: "DJJandU"<2712316242@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [kskin/WaterGAN] IndexError: list index out of range (#3)



@djjandXMU  同学你好，为了方便，我打中文了。我已经下载了NYU RGB-D dataset， 空气中的图像已经放到air_images，深度信息（mat文&#x4EF6;）已经放到air_depth当中。   一运行mainjamaica.py，https://github.com/kskin/WaterGAN/blob/3ad47608d20a9651fdf36ecb38b236e0942fae7b/modeljamaica.py#L743 就会报错ValueError: 'arr' does not have a suitable array shape for any mode. 请问你方便分享代码吗
 
&mdash;

**Comment by IPNUISTlegal** [comment]
谢谢你了，

**Comment by liuHuangshu110** [comment]
请问你是如何配置的这个环境，以及mat咋样生成的
